<?php

/**
 * @file
 * testie - Rick's demo module
 *
 * By Rick Smith of Cryptosmith
 *
 * This thing is too trivial to deserve protection 
 * through "intellectual property rights."
 *
 * This is my first attempt to write Drupal code
 * and I probably don't have the format quite right.
 *
 */

/* the menu hook - adds the path "/testie" to the site. */

function RAJATEC_menu(){
	$items['testie'] = array(
//		'title' => 'Example AJAX add to list',
		'title' => 'Get Current User Name',
		'page callback' => 'check_imei',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}




/* this code (noted in the callback above) creates the
 * contents of the "testie" page */
 
function check_imei(){

	return json_encode('test');
}
