<?php

/**
 * @file
 * testie - Rick's demo module
 *
 * By Rick Smith of Cryptosmith
 *
 * This thing is too trivial to deserve protection 
 * through "intellectual property rights."
 *
 * This is my first attempt to write Drupal code
 * and I probably don't have the format quite right.
 *
 */

/* the menu hook - adds the path "/testie" to the site. */

function RAJATEC_menu(){
	$items['testie'] = array(
//		'title' => 'Example AJAX add to list',
		'title' => 'Get Current User Name',
		'page callback' => 'check_imei',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}




/* this code (noted in the callback above) creates the
 * contents of the "testie" page */

function check_imei(){
	$imei = $_POST['imei'];
	$services_2 = views_get_view("warranty_api", true);
	$services_2->set_display("services_2");
	$services_2->set_exposed_input(array(
		'field_imei_2_value'=>$imei,
		'field_device_imei_number_value'=> $imei
	));
	$services_2->execute();
//	$view->result = array_merge($view->result, $services_2->result);
	header('Content-Type: application/json');
	return json_encode($services_2->result);
}
